# MongoDB Configuration
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://admin:UlXBiR5jYEmmFQSd@cluster0.pa8q59u.mongodb.net/smartcampus?retryWrites=true&w=majority}
spring.application.name=smartcampus
