# Server Port
server.port=8081

# MongoDB Configuration
# Replace with your local MongoDB URI or Atlas URI
spring.data.mongodb.uri=mongodb+srv://ayesha:ayesha123@cluster0.z4vowef.mongodb.net/smartcampus?appName=Cluster0

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.example.resourceapp=DEBUG

# Validation
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
